const data = [{
        name: "raspberry",
        background: "url(./Twinings_Assets/raspberry-BG.jpg)",
        headerImgUrl: "./Twinings_Assets/raspberry-new.png",
        headerBgUrl: "./Twinings_Assets/raspberry-tagline.png",
        product: "./Twinings_Assets/raspberry-product.png",
        teaElementTop: "./Twinings_Assets/raspberry - elements/Raspberry 2.png",
        teaElementTop2: "./Twinings_Assets/raspberry - elements/Raspberry 1.png",
        teaElementBottom: "./Twinings_Assets/raspberry - elements/Lemon.png",
        elementTop: "./Twinings_Assets/raspberry - elements/Raspberry 1.png",
        elementBottom: "./Twinings_Assets/raspberry - elements/petal - 3.png",
        smallElementRightTop: "./Twinings_Assets/raspberry - elements/petal - 3.png",
        smallElementRightBottom: "./Twinings_Assets/raspberry - elements/petal - 2.png",
        smallElementLeftBottom: "./Twinings_Assets/raspberry - elements/petal - 3.png",
        classHeader: "raspberry-head",
        classElementTop: "raspberry-top",
        classElementTop2: "raspberry-top-2",
        classElementBottom: "raspberry-bottom",
        classElementBottom2: "petal-4",
        classTeaElementTop2: "raspberry",
        classElementSmallRightTop: "petal-1",
        classElementSmallRightBottom: "petal-2",
        classSmallElementLeftBottom: "petal-3",

    },
    {
        name: "peach",
        background: "url(./Twinings_Assets/peach-BG.jpg)",
        headerImgUrl: "./Twinings_Assets/peach-newBanner.png",
        headerBgUrl: "./Twinings_Assets/peach-tagline.png",
        product: "./Twinings_Assets/peach-product.png",
        teaElementTop: "./Twinings_Assets/peach-elements/peach.png",
        teaElementTop2: "",
        teaElementBottom: "./Twinings_Assets/peach-elements/orange.png",
        elementTop: "",
        elementBottom: "",
        smallElementRightTop: "",
        smallElementRightBottom: "",
        smallElementLeftBottom: "",
        classHeader: "peach-head",
        classElementTop: "peach-top",
        classElementTop2: "none",
        classElementBottom: "peach-bottom",
        classElementBottom2: "none",
        classTeaElementTop2: "none",
        classElementSmallRightTop: "none",
        classElementSmallRightBottom: "none",
        classSmallElementLeftBottom: "none",
    },
    {
        name: "peppermint",
        background: "url(./Twinings_Assets/peppermint-BG.jpg)",
        headerImgUrl: "./Twinings_Assets/peppermint-newBanner.png",
        headerBgUrl: "./Twinings_Assets/upper tagline - 1.png",
        product: "./Twinings_Assets/peppermint-product.png",
        teaElementTop: "./Twinings_Assets/pepermint-elements/strawberry-2.png",
        teaElementTop2: "",
        teaElementBottom: "./Twinings_Assets/pepermint-elements/pepermint-1.png",
        elementTop: "./Twinings_Assets/pepermint-elements/strawberry-1.png",
        elementBottom: "./Twinings_Assets/pepermint-elements/pepermint-2.png",
        smallElementRightTop: "./Twinings_Assets/pepermint-elements/seed-2.png",
        smallElementRightBottom: "./Twinings_Assets/pepermint-elements/seed-1.png",
        smallElementLeftBottom: "",
        classHeader: "peppermint-head",
        classElementTop: "peppermint-top",
        classElementTop2: "strawberry-top",
        classElementBottom: "peppermint-bottom",
        classElementBottom2: "mint-bottom",
        classTeaElementTop2: "none",
        classElementSmallRightTop: "seed-top",
        classElementSmallRightBottom: "seed-bottom",
        classSmallElementLeftBottom: "none",
    },

]